vscode:
  extensions:
    - vscjava.vscode-spring-initializr@0.4.6:WOgtgIwX3Ngy4pM9ArXjCQ==
    - Pivotal.vscode-boot-dev-pack@0.0.8:BrfHu4se+ljgyUPUU+95ig==
    - vscjava.vscode-spring-boot-dashboard@0.1.8:HcUY2EBWUzLI8LYU/I2Flg==
    - Pivotal.vscode-spring-boot@1.17.0:mGdRFTP1eLVuk7lwGhEWRg==
    - JaimeOlivares.yuml@3.5.1:9ItqiLLuNnVQvJ7zYpbHZw==